require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

# React Native Maps dependencies
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'
pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'

target 'tbcRN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  # Permission handlers
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'OneSignal'


  target 'tbcRNTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
        deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        target_components = deployment_target.split

        if target_components.length > 0
          target_initial = target_components[0].to_i
          if target_initial < 9
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "9.0"
          end
        end
        if target.name == "React-Core-AccessibilityResources"
          target.remove_from_project
        end
      end
    end    
    react_native_post_install(installer)
  end
end
