enum EScreen {
  SIGN_UP,
  SIGN_IN,
  PUSH_NOTIFICATION,
  BOTTOMBREADCRUMBS,
  HOME,
  VENUE_DETAIL,
  WHATS_ON_OFFERS,
  TRENDING,
  EXPLORE,
  ORDER_TYPE,
  MAP,
  RELOAD_BANNER,
  VENUES_LIST,
  VENUE_DETAIL_ABOUT,
  VENUE_DETAIL_MENU,
  VENUE_DETAIL_WHATSON,
  VENUE_DETAIL_SEGMENT,
  PAYMENT_SENSE_CARD_SUCCESS,
  PAYMENT,
  MEMBER_DISCOUNT,
  MY_ORDERS,
  BUNDLE_BOGO
}

export default EScreen;
