name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install

      - run: yarn run clean && cd android && ./gradlew assembleRelease && cd ..
        name: Build Android apk (release)

      - name: Upload APK
        uses: actions/upload-artifact@v2-preview # This action will upload a build apk you can then test.
        with:
          name: app
          path: android/app/build/outputs/apk/release
