name: iOS OS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install && cd ios && pod install
        name: Build ipa for distribution
      - run: xcodebuild build -workspace "TheBarCode.xcworkspace" -scheme "TheBarCode"
      - name: Upload IPA
        uses: actions/upload-artifact@v2-preview # This action will upload a build apk you can then test.
        with:
          name: app
          path: $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
