name: iOS OS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: cd ios && pod install
      - name: Build ipa for distribution
      - run: xcode-project build-ipa --workspace "ios/TheBarCode.xcworkspace" --scheme TheBarCode
