name: iOS OS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install && cd ios && pod install
        name: Build ipa for distribution
      - run: cd ios && pod install && xcodebuild build -workspace "TheBarCode.xcworkspace" -scheme "TheBarCode" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      # - name: Upload APK
      #   uses: actions/upload-artifact@v2-preview # This action will upload a build apk you can then test.
      #   with:
      #     name: app
      #     path: $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
